In [1]:
# Importing useful libraries
import pandas as pd
import numpy as np

pd.options.display.max_columns = 100

In [2]:
# Importing the dataset
train_data = pd.read_csv("Trainfile.csv")
test_data = pd.read_csv("Testfile.csv")

In [3]:
train_data.head()

,Idx,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,45,RL,59.0,7227,Pave,NaN,Reg,HLS,AllPub,Corner,Mod,NAmes,Artery,Norm,1Fam,1.5Unf,6,6,1954,1954,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,TA,TA,No,Unf,0,Unf,0,832,832,GasA,Gd,Y,SBrkr,832,0,0,832,0,0,1,0,2,1,Gd,4,Typ,0,NaN,Detchd,1962.0,Unf,2,528,TA,TA,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal,105500
1,2,60,RL,NaN,12227,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NWAmes,PosN,Norm,1Fam,2Story,6,7,1977,1995,Gable,CompShg,HdBoard,HdBoard,BrkFace,424.0,TA,Gd,CBlock,Gd,Gd,No,ALQ,896,Unf,0,434,1330,GasA,TA,Y,SBrkr,1542,1330,0,2872,1,0,2,1,4,1,TA,11,Typ,1,TA,Attchd,1977.0,Fin,2,619,TA,TA,Y,550,282,0,0,0,0,NaN,NaN,NaN,0,7,2008,WD,Normal,272000
2,3,20,RL,65.0,7800,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Sawyer,Norm,Norm,1Fam,1Story,5,7,1967,2004,Hip,CompShg,HdBoard,HdBoard,BrkFace,89.0,TA,TA,PConc,TA,TA,No,ALQ,450,Unf,0,414,864,GasA,Ex,Y,SBrkr,899,0,0,899,0,0,1,0,3,1,Gd,5,Typ,0,NaN,Attchd,1967.0,Fin,1,288,TA,TA,Y,64,0,0,0,0,0,NaN,MnPrv,NaN,0,6,2009,WD,Normal,130000
3,4,60,RL,88.0,12665,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Timber,Norm,Norm,1Fam,2Story,8,5,2005,2006,Hip,CompShg,VinylSd,VinylSd,BrkFace,245.0,Gd,TA,PConc,Gd,Gd,Gd,Unf,0,Unf,0,1094,1094,GasA,Ex,Y,SBrkr,1133,1349,0,2482,0,0,2,1,4,1,Gd,9,Typ,1,Gd,BuiltIn,2005.0,Fin,3,642,TA,TA,Y,144,39,0,0,0,0,NaN,NaN,NaN,0,2,2007,WD,Normal,281213
4,5,20,RL,105.0,15431,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,1Fam,1Story,10,5,2008,2008,Hip,CompShg,VinylSd,VinylSd,Stone,200.0,Ex,TA,PConc,Ex,TA,Gd,GLQ,1767,ALQ,539,788,3094,GasA,Ex,Y,SBrkr,2402,0,0,2402,1,0,2,0,2,1,Ex,10,Typ,2,Gd,Attchd,2008.0,Fin,3,672,TA,TA,Y,0,72,0,0,170,0,NaN,NaN,NaN,0,4,2009,WD,Normal,555000

In [4]:
train_data.describe()

,Idx,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1138.000000,1138.000000,938.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1132.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1070.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000
mean,569.500000,57.618629,70.484009,10273.514060,6.111599,5.597540,1970.995606,1984.790861,102.795053,440.527241,42.954306,562.456063,1045.937610,1153.873462,355.300527,6.057996,1515.231986,0.425308,0.062390,1.556239,0.391037,2.873462,1.049209,6.538664,0.603691,1978.552336,1.750439,470.307557,90.373462,47.494728,23.067663,2.947276,14.570299,2.434974,40.179262,6.332162,2007.847100,179328.707381
std,328.656609,42.519037,24.983885,7742.762753,1.374100,1.112681,30.388180,20.618711,179.089584,452.563788,155.308430,442.891582,438.202684,385.710814,438.400418,49.254675,528.966115,0.518905,0.245577,0.549166,0.505892,0.822816,0.220426,1.636436,0.634860,24.434762,0.760228,217.823059,121.890193,67.077467,62.790978,25.120656,53.994274,36.868419,496.795058,2.722983,1.326741,76642.678880
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,0.000000,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.000000,1900.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,285.250000,20.000000,59.000000,7560.000000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,0.000000,216.000000,788.000000,866.750000,0.000000,0.000000,1130.250000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,5.000000,0.000000,1961.250000,1.000000,312.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129900.000000
50%,569.500000,50.000000,70.000000,9496.000000,6.000000,5.000000,1972.000000,1993.000000,0.000000,384.500000,0.000000,464.000000,984.000000,1080.000000,0.000000,0.000000,1469.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.000000,6.000000,1.000000,1979.000000,2.000000,478.000000,0.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,162450.000000
75%,853.750000,70.000000,80.000000,11596.000000,7.000000,6.000000,2000.000000,2004.000000,164.250000,706.000000,0.000000,796.750000,1268.000000,1378.000000,741.000000,0.000000,1774.000000,1.000000,0.000000,2.000000,1.000000,3.000000,1.000000,7.000000,1.000000,2002.000000,2.000000,576.000000,168.000000,72.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,210750.000000
max,1138.000000,190.000000,313.000000,159000.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1474.000000,2336.000000,6110.000000,4692.000000,2065.000000,572.000000,5642.000000,3.000000,2.000000,3.000000,2.000000,8.000000,3.000000,14.000000,3.000000,2010.000000,4.000000,1418.000000,857.000000,523.000000,552.000000,320.000000,410.000000,648.000000,15500.000000,12.000000,2010.000000,745000.000000

In [5]:
# Finding variables highly correlated with SalePrice
corr_matrix = train_data.corr()
corr_matrix["SalePrice"].sort_values(ascending=False)

SalePrice        1.000000
OverallQual      0.791583
GrLivArea        0.696450
GarageCars       0.643390
GarageArea       0.622827
TotalBsmtSF      0.583200
1stFlrSF         0.571859
FullBath         0.570665
YearBuilt        0.529717
TotRmsAbvGrd     0.523361
YearRemodAdd     0.522126
GarageYrBlt      0.495789
MasVnrArea       0.458281
Fireplaces       0.456931
LotFrontage      0.370337
2ndFlrSF         0.338577
BsmtFinSF1       0.334695
OpenPorchSF      0.316538
WoodDeckSF       0.309539
HalfBath         0.290770
LotArea          0.284774
BsmtUnfSF        0.238853
BsmtFullBath     0.213439
BedroomAbvGr     0.184831
ScreenPorch      0.138973
PoolArea         0.102545
MoSold           0.095011
3SsnPorch        0.064660
BsmtFinSF2      -0.010924
LowQualFinSF    -0.012313
YrSold          -0.022898
MiscVal         -0.025218
Idx             -0.027250
BsmtHalfBath    -0.036891
MSSubClass      -0.089530
OverallCond     -0.100036
EnclosedPorch   -0.139249
KitchenAbvGr    -0.141781
Name: SalePrice, dtype: float64

In [6]:
features = ['OverallQual','GrLivArea','GarageArea','TotalBsmtSF','1stFlrSF']

X_train = train_data[features]
X_test = test_data[features]
y_train = train_data['SalePrice']
y_test = test_data['SalePrice']

In [7]:
# Checking for null values
for col in X_train.columns:
    print(col,"has null values =",train_data[col].isnull().sum())

OverallQual has null values = 0
GrLivArea has null values = 0
GarageArea has null values = 0
TotalBsmtSF has null values = 0
1stFlrSF has null values = 0

In [8]:
X_train.head()

   OverallQual  GrLivArea  GarageArea  TotalBsmtSF  1stFlrSF
0            6        832         528          832       832
1            6       2872         619         1330      1542
2            5        899         288          864       899
3            8       2482         642         1094      1133
4           10       2402         672         3094      2402

In [9]:
def normaliser (df_train,df_test):
    
    temp_train = df_train.copy()
    temp_test = df_test.copy()
    
    for col in df_train.columns:
    
        max_value = df_train[col].max()
        min_value = df_train[col].min()
    
        temp_train[col] = (temp_train[col] - min_value) / (max_value - min_value)
        temp_test[col] = (temp_test[col] - min_value) / (max_value - min_value)

    return temp_train , temp_test

# Performing Normalisation
normalized_X_train , normalized_X_test = normaliser(X_train,X_test)

In [10]:
normalized_X_train.head()

   OverallQual  GrLivArea  GarageArea  TotalBsmtSF  1stFlrSF
0     0.555556   0.093821    0.372355     0.136170  0.114273
1     0.555556   0.478146    0.436530     0.217676  0.277191
2     0.444444   0.106443    0.203103     0.141408  0.129647
3     0.777778   0.404672    0.452750     0.179051  0.183341
4     1.000000   0.389601    0.473907     0.506383  0.474530

In [11]:
# Adding a column of ones for constant term

final_X_train = pd.DataFrame(np.concatenate((np.ones((normalized_X_train.shape[0],1)),normalized_X_train),axis=1))

final_X_test = pd.DataFrame(np.concatenate((np.ones((normalized_X_test.shape[0],1)),normalized_X_test),axis=1))

In [12]:
final_X_train.head()

     0         1         2         3         4         5
0  1.0  0.555556  0.093821  0.372355  0.136170  0.114273
1  1.0  0.555556  0.478146  0.436530  0.217676  0.277191
2  1.0  0.444444  0.106443  0.203103  0.141408  0.129647
3  1.0  0.777778  0.404672  0.452750  0.179051  0.183341
4  1.0  1.000000  0.389601  0.473907  0.506383  0.474530

In [13]:
# Finding coefficients (parameters) using the normal equation method
def normal_equation (X_train,y_train):
    return (np.linalg.inv(final_X_train.T@final_X_train))@(final_X_train.T)@y_train

theta = normal_equation(final_X_train,y_train)

In [14]:
y_pred = final_X_test @ theta

In [15]:
# Model Evaluation

# Cost Function
def cost_function(X_train, y_train, theta):
    m = len(y_train)
    J = np.sum(((X_train@theta) - y_train) ** 2)/(2 * m)
    return J

# R squared 
def r_squared (X_train,y_train,theta) :
    ssres = cost_function(X_train,y_train,theta)*2*X_train.shape[0]
    sstot = float(np.sum( (y_train - y_train.mean())**2 ))
    return 1-(ssres/sstot)

# Adjusted R squared
def adj_r_squared (X_train,y_train,theta):
    return 1 - (1-r_squared(X_train,y_train,theta))*(X_train.shape[0]-1)/(X_train.shape[0]-X_train.shape[1]-2)

# Mean Absolute Percentage Error
def mape (y,y_pred):
    mape = ( 100 / len(y) ) * sum( abs( (y-y_pred) / y ) )
    return mape

In [16]:
print("Mean absolute Percentage Error =",mape(y_test,y_pred),"\nR squared =",r_squared(final_X_train,y_train,theta.T),"\nAdjusted R squared =",adj_r_squared(final_X_train,y_train,theta.T))

Mean absolute Percentage Error = 14.345510557645385
R squared = 0.7458069362275332
Adjusted R squared = 0.7442322889298276